name: 📅 Daily Market Update

on:
  schedule:
    - cron: '0 9 * * *'  # Every day at 9:00 UTC
  workflow_dispatch:     # Optional: allows manual trigger

jobs:
  update-market-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run market report script
        run: python daily_report.py

      - name: Commit updated markdown file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add daily_market_update.md
          git commit -m "🧾 Daily Market Update - $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
